<?php

namespace Projet\AgendaBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * LoginRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LoginRepository extends EntityRepository
{
	
}
