projet_login_homepage:
    pattern:  /login
    defaults: { _controller: ProjetLoginBundle:Login:login }

projet_login_register:
    pattern: /register
    defaults: { _controller: ProjetLoginBundle:Login:register }
