parameters:
#    projet_login.example.class: Projet\LoginBundle\Example

services:
#    projet_login.example:
#        class: %projet_login.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
