projet_agenda_homepage:
    pattern:  /agenda
    defaults: { _controller: ProjetAgendaBundle:Agenda:agenda }

projet_agenda_add:
    pattern: /agenda/add
    defaults: { _controller: ProjetAgendaBundle:Agenda:ajouter }

projet_agenda_delete:
    pattern: /agenda/delete
    defaults: { _controller: ProjetAgendaBundle:Agenda:supprimer }