parameters:
#    projet_agenda.example.class: Projet\AgendaBundle\Example

services:
#    projet_agenda.example:
#        class: %projet_agenda.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
